# Generated by Django 6.0 on 2026-01-19 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('super_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.department'),
        ),
        migrations.AddField(
            model_name='documentcontrol',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_controls', to='super_admin.clients'),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='super_admin.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='super_admin.designation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.employee'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='super_admin.employee'),
        ),
        migrations.AddField(
            model_name='agent',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='super_admin.employee'),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='super_admin.employee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='super_admin.category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='super_admin.employee'),
        ),
        migrations.AddField(
            model_name='followup',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gst_invoices', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gst_invoices', to='super_admin.clients'),
        ),
        migrations.AddField(
            model_name='clientadvanceledger',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_admin.gstinvoice'),
        ),
        migrations.AddField(
            model_name='location',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='partymaster',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_admin.category'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='party_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='super_admin.partymaster'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='purchase_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grn', to='super_admin.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='super_admin.purchaseorder'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='branch.branch'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='super_admin.clients'),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gst_invoice', to='super_admin.quotation'),
        ),
        migrations.AddField(
            model_name='clients',
            name='quotation_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_for_companies', to='super_admin.quotation'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='super_admin.quotation'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='super_admin.clients'),
        ),
        migrations.AddField(
            model_name='clientadvanceledger',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_admin.receipt'),
        ),
        migrations.AddField(
            model_name='receiptallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='super_admin.gstinvoice'),
        ),
        migrations.AddField(
            model_name='receiptallocation',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='super_admin.receipt'),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='super_admin.employee'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='slab_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='super_admin.slabrate'),
        ),
        migrations.AddField(
            model_name='clients',
            name='slab_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_rules', to='super_admin.slabrate'),
        ),
        migrations.AlterUniqueTogether(
            name='clientsagent',
            unique_together={('client', 'agent')},
        ),
        migrations.AddIndex(
            model_name='deletedrecord',
            index=models.Index(fields=['content_type', 'object_id'], name='super_admin_content_aaa4c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentcontrol',
            unique_together={('clients', 'document_type', 'financial_year')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='salaryslip',
            unique_together={('employee', 'salary_date')},
        ),
    ]
