# Generated by Django 6.0 on 2026-01-19 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpermission',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='super_admin.clients'),
        ),
    ]
